# Generated by Django 4.2.10 on 2025-04-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('type', models.CharField(choices=[('car', 'Carro'), ('motorcycle', 'Motocicleta'), ('truck', 'Caminhão'), ('van', 'Van'), ('other', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Fabricante')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='Placa')),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='Número do Chassi')),
                ('status', models.CharField(choices=[('available', 'Disponível'), ('in_use', 'Em Uso'), ('maintenance', 'Em Manutenção'), ('retired', 'Aposentado')], default='available', max_length=20, verbose_name='Status')),
                ('mileage', models.IntegerField(verbose_name='Quilometragem')),
                ('fuel_type', models.CharField(max_length=50, verbose_name='Tipo de Combustível')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='Última Manutenção')),
                ('next_maintenance', models.DateField(blank=True, null=True, verbose_name='Próxima Manutenção')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['name'],
            },
        ),
    ]
