# Generated by Django 4.2.10 on 2025-04-24 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_vehicle_fuel_type_alter_vehicle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(max_length=100, unique=True, verbose_name='Número do Chassi'),
        ),
    ]
