# Generated by Django 4.2.10 on 2025-04-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('type', models.CharField(choices=[('tool', 'Ferramenta'), ('machine', 'Máquina'), ('safety', 'Equipamento de Segurança'), ('electronic', 'Equipamento Eletrônico'), ('other', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Fabricante')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='Número de Série')),
                ('status', models.CharField(choices=[('available', 'Disponível'), ('in_use', 'Em Uso'), ('maintenance', 'Em Manutenção'), ('retired', 'Aposentado')], default='available', max_length=20, verbose_name='Status')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Data de Compra')),
                ('warranty_expiry', models.DateField(blank=True, null=True, verbose_name='Fim da Garantia')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='Última Manutenção')),
                ('next_maintenance', models.DateField(blank=True, null=True, verbose_name='Próxima Manutenção')),
                ('location', models.CharField(max_length=100, verbose_name='Localização')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['name'],
            },
        ),
    ]
