# Generated by Django 4.2.10 on 2025-04-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('severity', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], max_length=20, verbose_name='Severidade')),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('investigating', 'Em Investigação'), ('resolved', 'Resolvido'), ('closed', 'Fechado')], default='open', max_length=20, verbose_name='Status')),
                ('reported_by', models.CharField(max_length=100, verbose_name='Reportado por')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='Reportado em')),
                ('location', models.CharField(max_length=100, verbose_name='Local')),
                ('affected_assets', models.TextField(verbose_name='Ativos Afetados')),
                ('resolution', models.TextField(blank=True, verbose_name='Resolução')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('resolved_by', models.CharField(blank=True, max_length=100, verbose_name='Resolvido por')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Incidente de Segurança',
                'verbose_name_plural': 'Incidentes de Segurança',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('access', 'Acesso'), ('alert', 'Alerta'), ('violation', 'Violação'), ('system', 'Sistema'), ('other', 'Outro')], max_length=20, verbose_name='Tipo de Evento')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('user', models.CharField(max_length=100, verbose_name='Usuário')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('device_id', models.CharField(blank=True, max_length=100, verbose_name='ID do Dispositivo')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Local')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Log de Segurança',
                'verbose_name_plural': 'Logs de Segurança',
                'ordering': ['-created_at'],
            },
        ),
    ]
